### ISSUE TITLE
Countdown timer in minutes suggestion

### ISSUE THREAD

**Issue by otejiri** [parteek111269/angular-otp-package#1]
It would be great to add an option to switch countdown timer in minutes or seconds.

**Comment by parteek111269** [comment]
Hi otejiri, I have added the option to switch the countdown between minutes or seconds.
Use the following option in setting
timerType: 0(seconds)/1(minutes)
For more information on the document, please refer below
github: https://github.com/parteek111269/angular-otp-package
npm: https://www.npmjs.com/package/angular-otp-box

Regards
